services:
  - type: web
    name: yatra-backend-server
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    env: static
    rootDir: server
    envVars:
      - key: PORT
        value: 5050
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
